CREATE TABLE IF NOT EXISTS MIGRATION(
  REVISION INTEGER NOT NULL PRIMARY KEY,
  DESCRIPTION VARCHAR(255) NOT NULL,
  STARTED DATETIME,
  COMPLETED DATETIME);

INSERT INTO MIGRATION (REVISION, DESCRIPTION, STARTED, COMPLETED)
  VALUES (0, 'INIT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
